<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE vehicles [
      <!ELEMENT vehicles (serie*,car*, truck*)>
      <!ELEMENT serie(idSerie, marca, modelo, anio_fabricacion)>
      <!ELEMENT idSerie EMPTY>
      <!ATTLIST idSerie numero CDATA #REQUIRED>
      <!ELEMENT marca EMPTY>
      <!ATTLIST marca tipo CDATA #REQUIRED>
      <!ELEMENT modelo EMPTY>
      <!ATTLIST modelo tipo CDATA #REQUIRED>
      <!ELEMENT anio_fabricacion EMPTY>
      <!ELEMENT car (numBastidor, matricula, colour, numAsientos, precio, numPuertas, capacidadMaletero, serie)>
      <!ELEMENT numBastidor EMPTY>
      <!ATTLIST numBastidor numero CDATA #REQUIRED>
      <!ELEMENT matricula EMPTY>
      <!ATTLIST matricula numero CDATA #REQUIRED>
      <!ELEMENT colour EMPTY>
      <!ATTLIST colour tipo CDATA #REQUIRED>
      <!ELEMENT numAsientos EMPTY>
      <!ATTLIST numAsientos cantidad CDATA #REQUIRED>
      <!ELEMENT precio EMPTY>
      <!ATTLIST precio total CDATA #REQUIRED>
      <!ELEMENT numPuertas EMPTY>
      <!ATTLIST numPuertas cantidad CDATA #REQUIRED>
      <!ELEMENT capacidadMaletero EMPTY>
      <!ATTLIST capacidadMaletero  cantidad CDATA #REQUIRED>
      <!ELEMENT serie EMPTY>
      <!ATTLIST serie numero CDATA #REQUIRED>
      <!ELEMENT truck (numBastidor, matricula, colour, numAsientos, precio, carga, tipoMercancia, serie)>
      <!ELEMENT carga EMPTY>
      <!ATTLIST carga cantidad CDATA #REQUIRED>
      <!ELEMENT tipoMercancia EMPTY>
      <!ATTLIST tipoMercancia tipo CDATA #REQUIRED>
]>


<vehicles>
<serie>
	idSerie numero="serie"></numBastidor>
	<marca numero="marca"></marca>
	<modelo tipo="modelo"></modelo>
	<anio_fabricacion tipo="anio"></anio_fabricacion>
</serie>
<car>
	<numBastidor numero="bastidor"></numBastidor>
	<matricula numero="matricula"></matricula>
	<colour tipo="color"></colour>
	<numAsientos cantidad="asientos"></numAsientos>
	<precio total="precio"></precio>
	<numPuertas cantidad="puertas"></numPuertas>
	<capacidadMaletero cantidad="capacidad"></capacidadMaletero>
	<serie numero="serie"></serie>

</car>

<truck>
	<numBastidor numero="bastidor"></numBastidor>
	<matricula numero="matricula"></matricula>
	<colour tipo="color"></colour>
	<numAsientos cantidad="asientos"></numAsientos>
	<precio total="precio"></precio>
	<carga cantidad="carga"></carga>
	<tipoMercancía tipo="mercancia"></tipoMercancía>
	<serie numero="serie"></serie>

</truck>
</vehicles>